"use client";

import { useState } from "react";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { useSoutenanceMutations, type SessionDetail } from "@/hooks/use-soutenances";
import { BRIEF_STATUSES, DEFAULT_BRIEF_STATUSES, type BriefStatus } from "@/lib/soutenance/types";
import { formatDateTime, formatUsd } from "@/lib/format";
import { cn } from "@/lib/utils";
import { EditableDoc, StepPanel } from "./DocPanel";

const STATUS_META: Record<BriefStatus, { label: string; stamp: string }> = {
  partial: { label: "Partiel", stamp: "stamp-partial" },
  fail: { label: "Non conforme", stamp: "stamp-fail" },
  roadmap: { label: "Roadmap", stamp: "stamp-roadmap" },
  pass_with_question: { label: "Conforme avec question", stamp: "stamp-pass" },
  pending: { label: "À évaluer", stamp: "stamp-pending" },
};

/**
 * The brief of the séance: the requirements it covers (by evaluation
 * status), generated by the « Soutenances » agent on the active version,
 * enriched with the synthèse's questions and the evaluators' own.
 */
export function BriefPanel({ rfpId, detail, canEdit }: { rfpId: string; detail: SessionDetail; canEdit: boolean }) {
  const { generateBrief, patchBrief } = useSoutenanceMutations(rfpId);
  const brief = detail.brief;
  const [statuses, setStatuses] = useState<BriefStatus[]>((brief?.target_statuses as BriefStatus[] | undefined)?.length ? (brief!.target_statuses as BriefStatus[]) : DEFAULT_BRIEF_STATUSES);
  const running = brief?.status === "pending" || brief?.status === "processing";
  const ready = brief?.status === "completed" && !!brief.report_markdown;

  const toggle = (s: BriefStatus) => setStatuses((prev) => (prev.includes(s) ? prev.filter((x) => x !== s) : [...prev, s]));

  const generate = async () => {
    if (statuses.length === 0) {
      toast.error("Choisissez au moins un statut.");
      return;
    }
    try {
      await generateBrief.mutateAsync({ supplierId: detail.supplier.id, statuses });
      toast.success("Brief lancé.");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Le brief n'a pas pu être lancé.");
    }
  };

  const state = running
    ? "Génération en cours"
    : ready
      ? `Généré le ${formatDateTime(brief!.completed_at ?? brief!.created_at)}${detail.overview.agents.soutenance ? ` · agent ${detail.overview.agents.soutenance.name}` : ""}${Number(brief!.cost) > 0 ? ` · ${formatUsd(Number(brief!.cost))}` : ""}${brief!.edited_at ? ` · modifié le ${formatDateTime(brief!.edited_at)}` : ""}`
      : brief?.status === "failed"
        ? `Échec : ${brief.error_message ?? "génération interrompue"}`
        : "Les points à clarifier en séance, à partir des exigences dont l'évaluation appelle une réponse.";

  return (
    <StepPanel
      id="brief"
      title="Brief"
      dot={ready ? "done" : running ? "now" : "todo"}
      state={state}
      actions={
        canEdit && (
          <Button type="button" variant={ready ? "ghost" : "outline"} size="sm" disabled={running || generateBrief.isPending} onClick={generate}>
            {running ? <Loader2 className="h-4 w-4 animate-spin" /> : ready ? <RefreshCw className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />}
            {ready ? "Régénérer" : "Générer le brief"}
          </Button>
        )
      }
    >
      <div role="group" aria-label="Exigences reprises dans le brief" className="inline-flex flex-wrap gap-1 self-start rounded-md border border-input bg-background p-0.5">
        {BRIEF_STATUSES.map((s) => {
          const on = statuses.includes(s);
          return (
            <button
              key={s}
              type="button"
              aria-pressed={on}
              disabled={!canEdit || running}
              onClick={() => toggle(s)}
              className={cn("inline-flex h-7 items-center gap-1.5 rounded-sm px-2 text-xs transition-colors duration-150 disabled:opacity-60", on ? "bg-muted font-medium text-foreground" : "text-muted-foreground hover:text-foreground")}
            >
              <span className={cn("stamp h-[18px] px-1.5", STATUS_META[s].stamp, !on && "opacity-50")}>{STATUS_META[s].label}</span>
            </button>
          );
        })}
      </div>
      <EditableDoc
        content={ready ? brief!.report_markdown : null}
        title={`Brief soutenance ${detail.supplier.name}`}
        canEdit={canEdit}
        onSave={(markdown) => patchBrief.mutateAsync({ supplierId: detail.supplier.id, brief_id: brief!.id, report_markdown: markdown })}
        saving={patchBrief.isPending}
        emptyText={running ? "Le brief arrive dans une à deux minutes ; la page se rafraîchit seule." : "Aucun brief pour cette séance. Choisissez les statuts à couvrir, puis générez-le."}
      />
    </StepPanel>
  );
}
