"use client";

import { useState } from "react";
import Link from "next/link";
import { Download, FileText, Loader2, Maximize2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { downloadDocx, useSoutenanceMutations, type Overview } from "@/hooks/use-soutenances";
import { syntheseMarkdown, syntheseTitle } from "@/lib/soutenance/documents";
import { formatDateTime, formatUsd } from "@/lib/format";
import { useIsMobile } from "@/hooks/use-mobile";
import { SyntheseTable } from "./SyntheseTable";
import { SupplierReading } from "./SupplierReading";

/**
 * The point de synthèse of the active version: the table of domain notes
 * for a quick read, the reading per supplier below, generated by the
 * organisation's « Point de synthèse » agent, exported for the meeting.
 */
export function SynthesePanel({ rfpId, overview, canEdit, onPresent }: { rfpId: string; overview: Overview; canEdit: boolean; onPresent: () => void }) {
  const isMobile = useIsMobile();
  const { generateSynthese, patchSynthese } = useSoutenanceMutations(rfpId);
  const retained = overview.suppliers.filter((s) => !s.removed);
  const [selected, setSelected] = useState<string | null>(null);
  const [confirm, setConfirm] = useState(false);
  const [exporting, setExporting] = useState<"docx" | "pptx" | null>(null);
  const synth = overview.synthese;
  const running = synth?.status === "running" || synth?.status === "pending";
  const generated = retained.filter((s) => synth?.data?.suppliers?.[s.id]?.generated_at).length;
  const noScores = overview.scores.overall.every((o) => o.score === null);

  const generate = async () => {
    setConfirm(false);
    try {
      await generateSynthese.mutateAsync();
      toast.success(`Synthèse lancée pour ${retained.length} fournisseur${retained.length > 1 ? "s" : ""}.`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "La synthèse n'a pas pu être lancée.");
    }
  };

  const exportDocx = async () => {
    setExporting("docx");
    try {
      await downloadDocx(syntheseMarkdown(overview), syntheseTitle(overview));
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Export impossible.");
    } finally {
      setExporting(null);
    }
  };

  const exportPptx = async () => {
    setExporting("pptx");
    try {
      const res = await fetch(`/api/rfps/${rfpId}/soutenances/synthese/export`, { method: "POST", credentials: "include" });
      if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error ?? "Export impossible.");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${syntheseTitle(overview)}.pptx`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Export impossible.");
    } finally {
      setExporting(null);
    }
  };

  return (
    <section id="synthese" className="panel mx-4 scroll-mt-4 md:mx-8" aria-labelledby="synthese-title">
      <div className="flex flex-wrap items-center gap-3 border-b border-border px-4 py-3 md:px-5">
        <span className={synth?.status === "completed" ? "h-2 w-2 shrink-0 rounded-full bg-status-pass" : running ? "h-2 w-2 shrink-0 rounded-full bg-status-partial" : "h-2 w-2 shrink-0 rounded-full border-[1.5px] border-input"} aria-hidden />
        <h2 id="synthese-title" className="text-base font-semibold">
          Point de synthèse
        </h2>
        <span className="min-w-0 flex-1 truncate text-xs text-muted-foreground">
          {running
            ? `Génération en cours · ${generated}/${retained.length} fournisseurs`
            : synth?.generated_at
              ? `Généré le ${formatDateTime(synth.generated_at)} · ${overview.version?.version_name ?? ""}${overview.agents.synthese ? ` · agent ${overview.agents.synthese.name}` : ""}${synth.cost > 0 ? ` · ${formatUsd(Number(synth.cost))}` : ""}`
              : synth?.status === "failed"
                ? `Échec : ${synth.error ?? "génération interrompue"}`
                : `Notes de la version ${overview.version?.version_name ?? ""}. Forces, faiblesses et questions se génèrent avec l'agent « Point de synthèse ».`}
        </span>
        <span className="flex items-center gap-1.5">
          {canEdit && (
            <Button type="button" variant={synth?.generated_at ? "ghost" : "outline"} size="sm" disabled={running || generateSynthese.isPending || noScores} onClick={() => (synth?.generated_at ? setConfirm(true) : generate())} title={noScores ? "Aucune note sur cette version" : undefined}>
              {running ? <Loader2 className="h-4 w-4 animate-spin" /> : synth?.generated_at ? <RefreshCw className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />}
              {synth?.generated_at ? "Régénérer" : "Générer la synthèse"}
            </Button>
          )}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button type="button" variant="outline" size="sm" disabled={!!exporting}>
                {exporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                Exporter
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onSelect={exportDocx}>
                <FileText className="mr-2 h-4 w-4" />
                Document Word (.docx)
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={exportPptx}>
                <FileText className="mr-2 h-4 w-4" />
                Présentation (.pptx)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          {!isMobile && (
            <Button type="button" variant="outline" size="sm" onClick={onPresent}>
              <Maximize2 className="h-4 w-4" />
              Présenter
            </Button>
          )}
        </span>
      </div>
      <div className="flex flex-col gap-3 px-4 py-4 md:px-5">
        {noScores ? (
          <p className="py-4 text-sm text-muted-foreground">
            Aucune note sur cette version : la synthèse se construit dès que des réponses sont notées, dans{" "}
            <Link href={`/dashboard/rfp/${rfpId}/evaluate`} className="text-accent-foreground hover:underline underline-offset-2">
              l&apos;Évaluation
            </Link>
            .
          </p>
        ) : (
          <>
            <SyntheseTable overview={overview} selectedId={selected ?? retained[0]?.id ?? null} onSelect={setSelected} />
            <p className="max-w-[70ch] text-xs text-muted-foreground">
              La moyenne ne compte que les fournisseurs retenus. Les fournisseurs retirés de la version restent lisibles, atténués ; le retrait se fait dans{" "}
              <Link href={`/dashboard/rfp/${rfpId}/parametres#fournisseurs`} className="text-accent-foreground hover:underline underline-offset-2">
                Paramètres › Fournisseurs
              </Link>
              .
            </p>
            <SupplierReading
              overview={overview}
              supplierId={selected ?? retained[0]?.id ?? null}
              onSelect={setSelected}
              canEdit={canEdit && !running}
              onSave={(input) => patchSynthese.mutateAsync(input)}
              saving={patchSynthese.isPending}
            />
          </>
        )}
      </div>

      <AlertDialog open={confirm} onOpenChange={setConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Régénérer le point de synthèse ?</AlertDialogTitle>
            <AlertDialogDescription>Les forces, faiblesses et questions actuelles, y compris vos modifications à la main, seront remplacées pour les {retained.length} fournisseurs retenus.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Annuler</AlertDialogCancel>
            <AlertDialogAction onClick={generate}>Régénérer</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </section>
  );
}
